import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Body from '../src/components/body.component'
import Header from '../src/components/header.component'
import useScript from '../src/hooks/useScript'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <>{useScript('./scripts/utils.js')}</>
      </Head>
      <Header />
      <Body />
    </div>
  )
}

export default Home
